<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCZEjw0H\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCZEjw0H/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCZEjw0H.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCZEjw0H\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCZEjw0H\App_KernelDevDebugContainer([
    'container.build_hash' => 'CZEjw0H',
    'container.build_id' => '8b2b5ae7',
    'container.build_time' => 1662399816,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCZEjw0H');
