<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTGx42EY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTGx42EY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTGx42EY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTGx42EY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTGx42EY\App_KernelDevDebugContainer([
    'container.build_hash' => 'TGx42EY',
    'container.build_id' => '493ce69a',
    'container.build_time' => 1669483364,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTGx42EY');
