<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW2bX1SN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW2bX1SN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW2bX1SN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW2bX1SN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW2bX1SN\App_KernelDevDebugContainer([
    'container.build_hash' => 'W2bX1SN',
    'container.build_id' => 'a7b337c5',
    'container.build_time' => 1664226401,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW2bX1SN');
