<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_symfony_ux-vue_dist_r-c26f88.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/app.css',
            ],
        ],
        'root' => [
            'js' => [
                '/build/runtime.js',
                '/build/root.js',
            ],
            'css' => [
                '/build/root.css',
            ],
        ],
        'homepage' => [
            'js' => [
                '/build/runtime.js',
                '/build/homepage.js',
            ],
            'css' => [
                '/build/homepage.css',
            ],
        ],
    ],
],

]];
