<?php

namespace ContainerVmcXTR7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFriendshipRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\FriendshipRepository' shared autowired service.
     *
     * @return \App\Repository\FriendshipRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\FriendshipRepository'] = new \App\Repository\FriendshipRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
