<?php

namespace ContainerVmcXTR7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHobbyRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\HobbyRepository' shared autowired service.
     *
     * @return \App\Repository\HobbyRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\HobbyRepository'] = new \App\Repository\HobbyRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
