<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], [], []],
    '{id}' => [['id'], ['_controller' => 'App\\Controller\\PageController::index'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/page']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'root' => [[], ['_controller' => 'App\\Controller\\RootController::index'], [], [['text', '/']], [], [], []],
    'success' => [[], ['_controller' => 'App\\Controller\\RootController::success'], [], [['text', '/success']], [], [], []],
    'test' => [['id'], ['_controller' => 'App\\Controller\\RootController::test'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/test']], [], [], []],
    'allUsers' => [[], ['_controller' => 'App\\Controller\\UsersController::allUsers'], [], [['text', '/users']], [], [], []],
    'usersByHobby' => [['hobbyId'], ['_controller' => 'App\\Controller\\UsersController::usersByHobby'], [], [['variable', '/', '[^/]++', 'hobbyId', true], ['text', '/users']], [], [], []],
];
